"""Create type

Revision ID: ccc2671e4ad8
Revises: d95c9ee33012
Create Date: 2024-07-17 22:29:45.118426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc2671e4ad8'
down_revision: Union[str, None] = 'd95c9ee33012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_price',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_type_price_id'), 'type_price', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_type_price_id'), table_name='type_price')
    op.drop_table('type_price')
    # ### end Alembic commands ###
