"""update tables

Revision ID: e566289ce4d1
Revises: c0b3faffc5fa
Create Date: 2024-07-27 12:13:28.946032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e566289ce4d1'
down_revision: Union[str, None] = 'c0b3faffc5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'image_url')
    # ### end Alembic commands ###
