"""update tables

Revision ID: 4d1db2c069c7
Revises: 4f994c27f9da
Create Date: 2024-07-24 16:30:34.211099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1db2c069c7'
down_revision: Union[str, None] = '4f994c27f9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('descriptions', sa.String(), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'address')
    op.drop_column('order', 'descriptions')
    # ### end Alembic commands ###
