"""add telegram column

Revision ID: 1945fcec8978
Revises: e5bc0bac5564
Create Date: 2024-07-20 17:07:43.422676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1945fcec8978'
down_revision: Union[str, None] = 'e5bc0bac5564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['telegram'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'telegram')
    # ### end Alembic commands ###
